on:
  pull_request:
  push:
    branches:
      - main

jobs:
  staticalize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - run: |
          deno task dev &
          until curl --output /dev/null --silent --head --fail http://127.0.0.1:8000; do
            printf '.'
            sleep 1
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSR_API: ${{ secrets.JSR_API }}

      - name: Download Staticalize
        run: |
          wget https://github.com/thefrontside/staticalize/releases/download/v0.0.1/staticalize-linux.tar.gz \
            -O /tmp/staticalize-linux.tar.gz
          tar -xzf /tmp/staticalize-linux.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/staticalize-linux

      - name: Staticalize
        run: |
          staticalize-linux \
            --site=http://127.0.0.1:8000 \
            --output=built \
            --base=https://effection-www.deno.dev/

      - run: npx pagefind --site built

      - uses: actions/upload-artifact@v4
        with:
          name: built
          path: built